/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void convertToJava() {
        App convertToJavaTest = new App();



//        assertEquals(6, correctresulte.size());
//    }


    }
}
